### ISSUE TITLE
ExternalMethod not working in Zope 5

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.ExternalMethod#13]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

There is not issue in opening and editing the ExternalMethod in the ZMI, as in Zope 4.5.1 (#12).

But in Zope 5, it is not functional. When calling it directly (for ex. opening the "Test" tab), it returns `<ExternalMethod at my_function>` instead of returning the function's return value.

### What I did:

Tried using external methods

### What I expect to happen:

The External Method returning the result of the called function

### What actually happened:

A runtime Error: `RuntimeError: external method could not be called because it is None`

Full traceback:

```
2020-10-30 15:51:39 ERROR [Zope.SiteErrorLog:252][waitress-3] 1604069499.2838360.3263083137771595 http://localhost:9650/do
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 364, in publish_module
  Module ZPublisher.WSGIPublisher, line 259, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Shared.DC.Scripts.Bindings, line 333, in __call__
  Module Shared.DC.Scripts.Bindings, line 370, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 351, in _exec
  Module script, line 1, in do
   - <PythonScript at /do>
   - Line 1
  Module Products.ExternalMethod.ExternalMethod, line 213, in __call__
RuntimeError: external method could not be called because it is None
2020-10-30 15:51:39 ERROR [waitress:357][waitress-3] Exception while serving /do
Traceback (most recent call last):
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 364, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 259, in publish
    result = mapply(obj,
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 68, in call_object
    return obj(*args)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 333, in __call__
    return self._bindAndExec(args, kw, None)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 370, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/PythonScripts/PythonScript.py", line 351, in _exec
    result = function(*args, **kw)
  File "Script (Python)", line 1, in do
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/ExternalMethod/ExternalMethod.py", line 213, in __call__
    raise RuntimeError('external method could not be called '
RuntimeError: external method could not be called because it is None
2020-10-30 15:58:07 ERROR [Zope.SiteErrorLog:252][waitress-1] 1604069887.4151240.4514830654598381 http://localhost:9650/do
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 364, in publish_module
  Module ZPublisher.WSGIPublisher, line 259, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Shared.DC.Scripts.Bindings, line 333, in __call__
  Module Shared.DC.Scripts.Bindings, line 370, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 351, in _exec
  Module script, line 1, in do
   - <PythonScript at /do>
   - Line 1
  Module Products.ExternalMethod.ExternalMethod, line 213, in __call__
RuntimeError: external method could not be called because it is None
2020-10-30 15:58:07 ERROR [waitress:357][waitress-1] Exception while serving /do
Traceback (most recent call last):
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 364, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 259, in publish
    result = mapply(obj,
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 68, in call_object
    return obj(*args)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 333, in __call__
    return self._bindAndExec(args, kw, None)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 370, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/PythonScripts/PythonScript.py", line 351, in _exec
    result = function(*args, **kw)
  File "Script (Python)", line 1, in do
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/ExternalMethod/ExternalMethod.py", line 213, in __call__
    raise RuntimeError('external method could not be called '
RuntimeError: external method could not be called because it is None
2020-10-30 15:59:53 ERROR [Zope.SiteErrorLog:252][waitress-1] 1604069993.0396850.6348794626388178 http://localhost:9650/do
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 364, in publish_module
  Module ZPublisher.WSGIPublisher, line 259, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Shared.DC.Scripts.Bindings, line 333, in __call__
  Module Shared.DC.Scripts.Bindings, line 370, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 351, in _exec
  Module script, line 1, in do
   - <PythonScript at /do>
   - Line 1
  Module Products.ExternalMethod.ExternalMethod, line 213, in __call__
RuntimeError: external method could not be called because it is None
2020-10-30 15:59:53 ERROR [waitress:357][waitress-1] Exception while serving /do
Traceback (most recent call last):
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 364, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 259, in publish
    result = mapply(obj,
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 68, in call_object
    return obj(*args)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 333, in __call__
    return self._bindAndExec(args, kw, None)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 370, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/PythonScripts/PythonScript.py", line 351, in _exec
    result = function(*args, **kw)
  File "Script (Python)", line 1, in do
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/ExternalMethod/ExternalMethod.py", line 213, in __call__
    raise RuntimeError('external method could not be called '
RuntimeError: external method could not be called because it is None
2020-10-30 16:00:16 ERROR [Zope.SiteErrorLog:252][waitress-1] 1604070016.9783180.21665200815515473 http://localhost:9650/do
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 364, in publish_module
  Module ZPublisher.WSGIPublisher, line 259, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Shared.DC.Scripts.Bindings, line 333, in __call__
  Module Shared.DC.Scripts.Bindings, line 370, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 351, in _exec
  Module script, line 1, in do
   - <PythonScript at /do>
   - Line 1
  Module Products.ExternalMethod.ExternalMethod, line 213, in __call__
RuntimeError: external method could not be called because it is None
2020-10-30 16:00:16 ERROR [waitress:357][waitress-1] Exception while serving /do
Traceback (most recent call last):
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 364, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 259, in publish
    result = mapply(obj,
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/ZPublisher/WSGIPublisher.py", line 68, in call_object
    return obj(*args)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 333, in __call__
    return self._bindAndExec(args, kw, None)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Shared/DC/Scripts/Bindings.py", line 370, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/PythonScripts/PythonScript.py", line 351, in _exec
    result = function(*args, **kw)
  File "Script (Python)", line 1, in do
  File "/Users/me/opt/myZope5/lib/python3.8/site-packages/Products/ExternalMethod/ExternalMethod.py", line 213, in __call__
    raise RuntimeError('external method could not be called '
RuntimeError: external method could not be called because it is None
```

### What version of Python and Zope/Addons I am using:

- Python 3.8.6
- Zope 5.0
- ExternalMethod 4.4

**Comment by dataflake** [comment]
It would be helpful if you posted the code of your external method and the code of the Python Script that you use to call that External Method. I cannot reproduce the traceback in my sandbox.

**Comment by georgpfolz** [comment]
That's weird, after a restart of the server it works now (with exactly the same EM). Sorry for the bother.
